### ISSUE TITLE
VueJS

### ISSUE THREAD

**Issue by karneaud** [interfaced/zombiebox#1]
Has anyone ever used this with VueJS framework?

**Comment by l1bbcsg** [comment]
Not as far as we're aware. 

There were pretty successful attempts at using it with other frameworks similar enough to Vue however.

Generally it should be possible but will likely require sacrificing some parts of either ZombieBox or Vue functionality since they attempt to solve a lot of the same problems, so this might not be a good idea. 

Major ZombieBox components like spatial navigation, focus management, history management or ui toolkit might not work properly with typical Vue app out of the box and likely require some workarounds.
Same should be true for core Vue components, practices and approaches.

Most sane approach is probably using only hardware abstraction layer from ZombieBox: classes in device directory and array of ZombieBox platforms packages.

**Comment by karneaud** [comment]
understood
